program 1
Amritha Narayanankutty
roll no: 6

In [2]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)
print("first column\n")
print(x[::,0])
print("second column\n")
print(x[::,1])
print("third column\n")
print(x[::,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
first column

[0 3 6]
second column

[1 4 7]
third column

[2 5 8]


In [1]:
import numpy as np
m1=np.arange(9).reshape(3,3)
m2=np.array([[2,4,6],[7,5,9],[8,2,5]])
print(m1)
print(m2)
print("Multiplication:\n",np.matmul(m1,m2))
print("Multiplication:\n",m1+m2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 4 6]
 [7 5 9]
 [8 2 5]]
Multiplication:
 [[ 23   9  19]
 [ 74  42  79]
 [125  75 139]]
Multiplication:
 [[ 2  5  8]
 [10  9 14]
 [14  9 13]]


In [11]:
import numpy as np
m1=np.array([[2,4,6],[7,5,9],[8,2,5]])
w,v=np.linalg.eig(m1)
print(w)
print(v)

[15.24087    -3.11446688 -0.12640311]
[[-0.44925205 -0.66913741 -0.1805784 ]
 [-0.74303263 -0.21256413 -0.78763456]
 [-0.49605958  0.71208961  0.58908679]]


In [12]:
import numpy as np
m1=np.array([[2,4,6],[7,5,9],[8,2,5]])
v=np.linalg.eig(m1)
print(v)

(array([15.24087   , -3.11446688, -0.12640311]), array([[-0.44925205, -0.66913741, -0.1805784 ],
       [-0.74303263, -0.21256413, -0.78763456],
       [-0.49605958,  0.71208961,  0.58908679]]))


In [13]:
import numpy as np
m1=np.array([[2,4,6],[7,5,9],[8,2,5]])
print("Transpose\n",np.transpose(m1))
print("Determinant\n",np.linalg.det(m1))
print("Inverse\n",np.linalg.inv(m1))

Transpose
 [[2 7 8]
 [4 5 2]
 [6 9 5]]
Determinant
 6.000000000000003
Inverse
 [[ 1.16666667 -1.33333333  1.        ]
 [ 6.16666667 -6.33333333  4.        ]
 [-4.33333333  4.66666667 -3.        ]]
