In [2]:
#p1
import numpy as np
arr=np.arange(1,15)
print(arr)
print(arr.size)
num=int(input("Enter number to be updated"))
arr[8]=num
print(arr)
arr1=arr[::-1]
print(arr1)
arr2=arr.reshape(7,2)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14
Enter number to be updated20
[ 1  2  3  4  5  6  7  8 20 10 11 12 13 14]
[14 13 12 11 10 20  8  7  6  5  4  3  2  1]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [20 10]
 [11 12]
 [13 14]]


In [3]:
#p2
import numpy as np
x=np.arange(12,32).reshape(5,4)
print(x)
print("Shape",x.shape)
print("type",type(x))
print("datatype",x.dtype)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Shape (5, 4)
type <class 'numpy.ndarray'>
datatype int64


In [4]:
#p3
import numpy as  np
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#p4
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,4,6])
print(arr1)
print(arr2)
print("Comparison: ",np.in1d(arr1,arr2))

[1 2 3 4 5]
[2 4 6]
Comparison:  [False  True False  True False]


In [6]:
#p5
import numpy as np
arr1=np.array([0,1,2,3,4])
arr2=np.array([1,2,3,6,7])
print("Union: ",np.union1d(arr1,arr2))
print("Intersection: ",np.intersect1d(arr1,arr2))

Union:  [0 1 2 3 4 6 7]
Intersection:  [1 2 3]


In [7]:
#p6
import numpy as np
arr1=np.array([1,2,3,3,4,4,5])
print("Uniquely: ",np.unique(arr1))

Uniquely:  [1 2 3 4 5]


In [9]:
#p7
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
l1=arr.tolist()
print(l1)
print(type(l1))

[ 1  2  3  4  5  6  7  8 20 10 11 12 13 14]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 20, 10, 11, 12, 13, 14]
<class 'list'>
